const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpeg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/pant1.jpeg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      category: "Pants",
      image: "/images/pant2.jpeg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },

    {
      name: "Watch Rolex",
      slug: "watch-rolex",
      category: "watches",
      image: "/images/watch1.jpeg",
      price: 125,
      countInStock: 9,
      brand: "Rolex",
      rating: 4.8,
      numReviews: 8,
      description: "high quality watch",
    },
    {
      name: "Watch Brand",
      slug: "watch-brand",
      category: "watches",
      image: "/images/watch2.jpeg",
      price: 2500,
      countInStock: 19,
      brand: "Brand",
      rating: 4.2,
      numReviews: 10,
      description: "high quality brand",
    },
    {
      name: "HP15",
      slug: "hp15",
      category: "laptops",
      image: "/images/laptop1.jpeg",
      price: 54000,
      countInStock: 17,
      brand: "HP",
      rating: 4.9,
      numReviews: 16,
      description: "high quality laptop",
    },
    {
      name: "Lenovo Thinkpad",
      slug: "lenovo-thinkpad",
      category: "laptops",
      image: "/images/laptop2.jpeg",
      price: 65000,
      countInStock: 7,
      brand: "lenovo",
      rating: 4.8,
      numReviews: 11,
      description: "high quality laptop",
    },
  ],
};
export default data;
